version: '3.7'
services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - var_lib_mysql:/var/lib/mysql
    expose:
      - "3306"
  slurmctld:
    image: computationalplantscience/plantit-sandbox
    command: ["slurmctld"]
    working_dir: /opt/plantit-cli/runs
    hostname: slurmctld
    privileged: true
    environment:
      - CYVERSE_USERNAME=${CYVERSE_USERNAME}
      - CYVERSE_PASSWORD=${CYVERSE_PASSWORD}
      - COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}
      - TEST_DIRECTORY=${TEST_DIRECTORY}
    volumes:
      - .:/opt/plantit-cli/
      - ./config/dask/:/root/.config/dask/
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6817"
    depends_on:
      - slurmdbd
  slurmdbd:
    image: giovtorres/slurm-docker-cluster
    hostname: slurmdbd
    command: ["slurmdbd"]
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql
  c1:
    image: computationalplantscience/plantit-sandbox
    hostname: c1
    working_dir: /opt/plantit-cli/runs
    command: ["slurmd"]
    privileged: true
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - .:/opt/plantit-cli/
    expose:
      - "6818"
    depends_on:
      - slurmctld
  c2:
    image: computationalplantscience/plantit-sandbox
    hostname: c2
    command: ["slurmd"]
    working_dir: /opt/plantit-cli/runs
    privileged: true
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - .:/opt/plantit-cli/
    expose:
      - "6818"
    depends_on:
      - slurmctld
volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm: